spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB:price_tracker}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  application:
    name: price-tracker